using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;
using RealState.Application.Entities;
using RealState.Application.Enums;
using RealState.Web.Areas.Suppliers.Models;

namespace RealState.Web.Areas.Sales.Models;

// Product sales invoices (فواتير المبيعات). The product-lines editor is the purchasing one (_DocItems), so a line's
// unit selling price travels in DocItemInput.Cost.

// ---------- Invoice CRUD ----------
public class SalesInvoiceFormModel
{
    public Guid Id { get; set; }
    /// <summary>Display only: the invoice's number, or the number the next new invoice will take.</summary>
    public int Number { get; set; }

    [Required(ErrorMessage = "العميل مطلوب")]
    [Display(Name = "العميل")]
    public Guid? CustomerId { get; set; }

    [Display(Name = "المخزن (صرف الأصناف المخزنية)")]
    public Guid? WarehouseId { get; set; }

    [Required][DataType(DataType.Date)][Display(Name = "تاريخ الفاتورة")]
    public DateTime InvoiceDate { get; set; } = DateTime.Today;

    [Display(Name = "ملاحظات")]
    public string? Notes { get; set; }

    /// <summary>Lines — <see cref="DocItemInput.Cost"/> holds the unit selling price (سعر البيع).</summary>
    public List<DocItemInput> Items { get; set; } = new();

    public List<SelectListItem> Customers { get; set; } = new();
    public List<SelectListItem> Warehouses { get; set; } = new();
    public List<ProductOption> Products { get; set; } = new();
}

// ---------- Invoices list ----------
public class SalesInvoiceListItem
{
    public Guid Id { get; set; }
    public int Number { get; set; }
    public DateTime InvoiceDate { get; set; }
    public Guid CustomerId { get; set; }
    public string Customer { get; set; } = string.Empty;
    public decimal Total { get; set; }
    public int ItemCount { get; set; }
    public decimal Collected { get; set; }
    public decimal Remaining => Total - Collected;
}

/// <summary>A goods issue generated by a sales invoice, with the cost of sales it booked.</summary>
public record SalesInvoiceIssueRef(Guid Id, int Number, DateTime Date, InventoryDocStatus Status, decimal Cost);

/// <summary>Invoice details page: the invoice plus display names resolved for its references.</summary>
public class SalesInvoiceDetailsVm
{
    public ProductSalesInvoice Invoice { get; set; } = default!;
    public string Customer { get; set; } = "—";
    public string? CustomerPhone { get; set; }
    public string? Warehouse { get; set; }
    /// <summary>The invoice's automatic goods issues — the current (posted) one plus any reversed by edits.</summary>
    public List<SalesInvoiceIssueRef> Issues { get; set; } = new();
    public decimal Total => Invoice.Items.Sum(i => i.LineTotal);
    public decimal Collected => Invoice.Collections.Sum(c => c.Amount);
    public decimal Remaining => Total - Collected;
    /// <summary>Cost of sales booked by the posted goods issue (costing method), for the gross profit.</summary>
    public decimal CostOfSales => Issues.Where(i => i.Status == InventoryDocStatus.Posted).Sum(i => i.Cost);
    public decimal GrossProfit => Total - CostOfSales;
}

// ---------- Collection form ----------
public class SalesCollectFormModel
{
    public Guid InvoiceId { get; set; }
    public string DocumentLabel { get; set; } = string.Empty;
    public decimal Total { get; set; }
    public decimal Collected { get; set; }
    public decimal Remaining { get; set; }

    [Range(0.01, 999999999999, ErrorMessage = "المبلغ غير صالح")]
    [Display(Name = "المبلغ المحصَّل (ج.م)")]
    public decimal Amount { get; set; }

    [Required(ErrorMessage = "اختر الخزنة")]
    [Display(Name = "الخزنة")]
    public Guid? SafeId { get; set; }

    [Required][DataType(DataType.Date)][Display(Name = "تاريخ التحصيل")]
    public DateTime CollectedDate { get; set; } = DateTime.Today;

    [Display(Name = "ملاحظات")]
    public string? Description { get; set; }

    public List<SelectListItem> Safes { get; set; } = new();
}

// ---------- Sales summary (landing page of «المبيعات») ----------
/// <summary>A customer figure on the sales summary (top buyers / outstanding balances).</summary>
public record CustomerAmount(Guid CustomerId, string Customer, decimal Value, int Invoices);

/// <summary>A recent invoice on the sales summary.</summary>
public record RecentSalesInvoice(Guid Id, int Number, string Customer, decimal Total, decimal Remaining, DateTime Date);

/// <summary>Product sales invoices + their customers at a glance — the counterpart of the contracts summary.</summary>
public class SalesInvoiceSummaryVm
{
    public int InvoicesCount { get; set; }
    public decimal TotalSales { get; set; }
    public decimal TotalCollected { get; set; }
    public decimal TotalRemaining => TotalSales - TotalCollected;
    /// <summary>Cost of sales booked by the invoices' posted goods issues (costing method).</summary>
    public decimal CostOfSales { get; set; }
    public decimal GrossProfit => TotalSales - CostOfSales;
    public decimal MarginPct => TotalSales > 0 ? Math.Round(GrossProfit / TotalSales * 100, 1) : 0;
    public decimal AvgInvoice => InvoicesCount > 0 ? Math.Round(TotalSales / InvoicesCount, 2) : 0;

    /// <summary>Customers that have at least one sales invoice.</summary>
    public int BuyingCustomers { get; set; }
    /// <summary>Customers with an outstanding balance on their invoices.</summary>
    public int CustomersWithBalance { get; set; }

    // Month-over-month (current vs previous calendar month).
    public decimal SalesThisMonth { get; set; }
    public decimal SalesPrevMonth { get; set; }
    public decimal CollectedThisMonth { get; set; }
    public decimal CollectedPrevMonth { get; set; }
    public int InvoicesThisMonth { get; set; }
    public int InvoicesPrevMonth { get; set; }
    /// <summary>Customers whose first sales invoice falls in the month.</summary>
    public int NewBuyersThisMonth { get; set; }
    public int NewBuyersPrevMonth { get; set; }

    public List<MonthlySales> ByMonth { get; set; } = new();
    public List<CustomerAmount> TopCustomers { get; set; } = new();
    public List<CustomerAmount> TopDebtors { get; set; } = new();
    public List<RecentSalesInvoice> Latest { get; set; } = new();
}
